# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 10:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_first', models.EmailField(max_length=254)),
                ('email_second', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Контакты',
                'order_prefix': ' ',
                'verbose_name_plural': ' Контакты',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_ru', models.CharField(max_length=100, verbose_name='Должность')),
                ('position_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('position_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Имя')),
                ('name_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя')),
                ('surname_ru', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('surname_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('surname_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия')),
                ('description_ru', models.TextField(max_length=1000, verbose_name='Биография')),
                ('description_uk', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Биография')),
                ('description_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Биография')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'order_prefix': '    ',
                'verbose_name_plural': '    Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Functionality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=500, verbose_name='Название')),
                ('title_uk', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=500, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Функциональность',
                'verbose_name_plural': 'Функциональность',
            },
        ),
        migrations.CreateModel(
            name='GetInTouch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('text_ru', models.TextField(max_length=1000, verbose_name='Текст')),
                ('text_uk', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок "Get In Touch"',
                'order_prefix': '       ',
                'verbose_name_plural': '       Блок "Get In Touch"',
            },
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('headline_ru', models.CharField(max_length=200, verbose_name='Деятельность')),
                ('headline_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Деятельность')),
                ('headline_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Деятельность')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название компании')),
                ('title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании')),
                ('bottomline_ru', models.CharField(max_length=200, verbose_name='Слоган')),
                ('bottomline_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган')),
                ('bottomline_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган')),
            ],
            options={
                'verbose_name': 'Блок "Intro"',
                'order_prefix': '          ',
                'verbose_name_plural': '          Блок "Intro"',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Значение')),
                ('extra', models.BooleanField(default=False, verbose_name='Плюсик')),
                ('description_ru', models.CharField(max_length=50, verbose_name='Описание')),
                ('description_uk', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
                ('description_en', models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Employee')),
            ],
            options={
                'verbose_name': 'Цифра',
                'verbose_name_plural': 'Цифры',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visual_class', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=50)),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название')),
                ('title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('intro_phrase_ru', models.CharField(max_length=200, verbose_name='Вступительная фраза')),
                ('intro_phrase_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вступительная фраза')),
                ('intro_phrase_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Вступительная фраза')),
                ('description_short_ru', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('description_short_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание')),
                ('description_short_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание')),
                ('description_full_ru', models.TextField(max_length=1000, verbose_name='Подробное описание')),
                ('description_full_uk', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Подробное описание')),
                ('description_full_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Подробное описание')),
                ('description_functionality_ru', models.TextField(max_length=1000, verbose_name='Описание функциональности')),
                ('description_functionality_uk', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание функциональности')),
                ('description_functionality_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание функциональности')),
                ('description_scope_ru', models.TextField(max_length=1000, verbose_name='Описание сферы применения')),
                ('description_scope_uk', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание сферы применения')),
                ('description_scope_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание сферы применения')),
                ('completion', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Готовность стадии (%)')),
            ],
            options={
                'verbose_name': 'Проект',
                'order_prefix': '  ',
                'verbose_name_plural': '  Проекты',
            },
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название')),
                ('title_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Project')),
            ],
            options={
                'verbose_name': 'Cфера прменения',
                'verbose_name_plural': 'Сферы применения',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_ru', models.CharField(max_length=100, verbose_name='Услуга')),
                ('action_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Услуга')),
                ('action_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Услуга')),
                ('subject_ru', models.CharField(max_length=200, verbose_name='Объект услуги')),
                ('subject_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Объект услуги')),
                ('subject_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Объект услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'order_prefix': '     ',
                'verbose_name_plural': '     Услуги',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название')),
                ('title_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Стадия',
                'order_prefix': '   ',
                'verbose_name_plural': '   Стадии',
            },
        ),
        migrations.CreateModel(
            name='WeAre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('headline_ru', models.CharField(max_length=200, verbose_name='Определение')),
                ('headline_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Определение')),
                ('headline_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Определение')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('text_ru', models.TextField(max_length=1000, verbose_name='Текст')),
                ('text_uk', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок "We Are"',
                'order_prefix': '         ',
                'verbose_name_plural': '         Блок "We Are"',
            },
        ),
        migrations.CreateModel(
            name='WhatWeDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text_ru', models.TextField(max_length=1000, verbose_name='Текст')),
                ('text_uk', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('text_en', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок "What We Do"',
                'order_prefix': '        ',
                'verbose_name_plural': '        Блок "What We Do"',
            },
        ),
        migrations.CreateModel(
            name='WorkWithUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title_ru', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('text_ru', models.CharField(max_length=1000, verbose_name='Текст')),
                ('text_uk', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('text_en', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Блок "Work With Us"',
                'order_prefix': '      ',
                'verbose_name_plural': '      Блок "Work With Us"',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Stage'),
        ),
        migrations.AddField(
            model_name='number',
            name='we_are',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.WeAre'),
        ),
        migrations.AddField(
            model_name='functionality',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Project'),
        ),
    ]
