# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_first',
            field=models.CharField(default='+380 (93) 514-14-85', max_length=19, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_first',
            field=models.EmailField(max_length=254, verbose_name='E-mail #1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_second',
            field=models.EmailField(max_length=254, verbose_name='E-mail #2'),
        ),
    ]
