# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': ' Контакты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': '   Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='getintouch',
            options={'verbose_name': 'Блок "Get In Touch"', 'verbose_name_plural': '    Блок "Get In Touch"'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'Блок "Intro"', 'verbose_name_plural': '       Блок "Intro"'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': '  Проекты'},
        ),
        migrations.AlterModelOptions(
            name='weare',
            options={'verbose_name': 'Блок "We Are"', 'verbose_name_plural': '      Блок "We Are"'},
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name': 'Блок "What We Do"', 'verbose_name_plural': '     Блок "What We Do"'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='position_ru',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='surname',
            new_name='surname_ru',
        ),
        migrations.RenameField(
            model_name='functionality',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='getintouch',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='getintouch',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='bottomline',
            new_name='bottomline_ru',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='headline',
            new_name='headline_ru',
        ),
        migrations.RenameField(
            model_name='intro',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='number',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='additional',
            new_name='additional_ru',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_full',
            new_name='description_full_ru',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_short',
            new_name='description_short_ru',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='stage',
            new_name='stage_ru',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='weare',
            old_name='headline',
            new_name='headline_ru',
        ),
        migrations.RenameField(
            model_name='weare',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.RenameField(
            model_name='weare',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='whatwedo',
            old_name='text',
            new_name='text_ru',
        ),
        migrations.AddField(
            model_name='employee',
            name='description_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='employee',
            name='description_uk',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='name_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='employee',
            name='surname_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='functionality',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='functionality',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='getintouch',
            name='text_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='getintouch',
            name='text_uk',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='getintouch',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='getintouch',
            name='title_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='intro',
            name='bottomline_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='intro',
            name='bottomline_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='intro',
            name='headline_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Деятельность'),
        ),
        migrations.AddField(
            model_name='intro',
            name='headline_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Деятельность'),
        ),
        migrations.AddField(
            model_name='intro',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='intro',
            name='title_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='number',
            name='description_en',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='number',
            name='description_uk',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='additional_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='project',
            name='additional_uk',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_full_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_full_uk',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Подробное описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_short_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_short_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='project',
            name='stage_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Стадия'),
        ),
        migrations.AddField(
            model_name='project',
            name='stage_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Стадия'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='scope',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='scope',
            name='title_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='weare',
            name='headline_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Определение'),
        ),
        migrations.AddField(
            model_name='weare',
            name='headline_uk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Определение'),
        ),
        migrations.AddField(
            model_name='weare',
            name='text_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='weare',
            name='text_uk',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='weare',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='weare',
            name='title_uk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок'),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='text_en',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='whatwedo',
            name='text_uk',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
    ]
