# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_number_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionality',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='title_ru',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='functionality',
            name='title_uk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='number',
            name='extra',
            field=models.BooleanField(default=False, verbose_name='Плюсик'),
        ),
        migrations.AlterField(
            model_name='project',
            name='additional_ru',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Дополнительно'),
        ),
    ]
