# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20160412_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='stage_ru',
            new_name='stage',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stage_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stage_uk',
        ),
    ]
