# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160412_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название')),
                ('title_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'order_prefix': '  ',
                'verbose_name': 'Стадия',
                'verbose_name_plural': '  Стадии',
            },
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': '    Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='getintouch',
            options={'verbose_name': 'Блок "Get In Touch"', 'verbose_name_plural': '     Блок "Get In Touch"'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'Блок "Intro"', 'verbose_name_plural': '        Блок "Intro"'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': '   Проекты'},
        ),
        migrations.AlterModelOptions(
            name='weare',
            options={'verbose_name': 'Блок "We Are"', 'verbose_name_plural': '       Блок "We Are"'},
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name': 'Блок "What We Do"', 'verbose_name_plural': '      Блок "What We Do"'},
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.Stage'),
        ),
    ]
