# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20160412_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект', 'verbose_name_plural': '  Проекты'},
        ),
        migrations.AlterModelOptions(
            name='stage',
            options={'verbose_name': 'Стадия', 'verbose_name_plural': '   Стадии'},
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.Stage'),
        ),
    ]
