# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20160412_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_ru', models.CharField(max_length=100, verbose_name='Услуга')),
                ('action_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Услуга')),
                ('action_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Услуга')),
                ('subject_ru', models.CharField(max_length=200, verbose_name='Объект услуги')),
                ('subject_uk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Объект услуги')),
                ('subject_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='Объект услуги')),
            ],
            options={
                'verbose_name_plural': '     Услуги',
                'order_prefix': '     ',
                'verbose_name': 'Услуга',
            },
        ),
        migrations.AlterModelOptions(
            name='getintouch',
            options={'verbose_name': 'Блок "Get In Touch"', 'verbose_name_plural': '      Блок "Get In Touch"'},
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'Блок "Intro"', 'verbose_name_plural': '         Блок "Intro"'},
        ),
        migrations.AlterModelOptions(
            name='weare',
            options={'verbose_name': 'Блок "We Are"', 'verbose_name_plural': '        Блок "We Are"'},
        ),
        migrations.AlterModelOptions(
            name='whatwedo',
            options={'verbose_name': 'Блок "What We Do"', 'verbose_name_plural': '       Блок "What We Do"'},
        ),
    ]
