# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_name', models.CharField(max_length=100, verbose_name='Роутинг')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название страницы')),
                ('title_uk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название страницы')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название страницы')),
                ('description_ru', models.CharField(max_length=250, verbose_name='Описание страницы')),
                ('description_uk', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание страницы')),
                ('description_en', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание страницы')),
                ('robots', models.CharField(max_length=100, verbose_name='Информация для ботов')),
            ],
            options={
                'verbose_name': 'Метаданные',
                'verbose_name_plural': 'Метаданные',
            },
        ),
    ]
