# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_auto_20160412_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='metadata',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='metadata',
            name='description_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='description_uk',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='title_uk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
